# fake-ci.yml — realistic but illustrative CI workflow for a Vite + React project
# This is intentionally a "fake" extra workflow file; its steps are fully valid and can run in GitHub Actions.
# Trigger: pushes and PRs to main and on schedule (daily).

name: Fake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint (if configured)
        if: hashFiles('**/.eslintrc*') != ''
        run: npm run lint --if-present

      - name: Run tests
        run: npm test -- --watchAll=false
        env:
          CI: true

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifact (fake / optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fake-ci-build
          path: |
            dist
            build

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run npm audit (quick scan)
        run: |
          npm ci
          npm audit --audit-level=moderate || true

